def do_twice(f, g):
    f(g)
    f(g)

def print_spam(g):
    print(g)

def print_twice(b):
    print(b, end='')
    print(b, end='')

def print_three(b):
    print_twice(b)
    print(b, end='')

def do_four(a, b):
    do_twice(a, b)

def print_four(b):
    print_twice(b)
    print_twice(b)

def square1():
    print('+', end='')
    print_twice('---+')    
    print()
    print('|', end='')
    print_twice('   |')
    print()
    print('|', end='')
    print_twice('   |')
    print()
    print('|', end='')
    print_twice('   |')
    print()
    print('|', end='')
    print_twice('   |')
    print()
    print('+', end='')
    print_twice('---+')
    print()
    print('|', end='')
    print_twice('   |')
    print()
    print('|', end='')
    print_twice('   |')
    print()
    print('|', end='')
    print_twice('   |')
    print()
    print('|', end='')
    print_twice('   |')
    print()
    print('+', end='')
    print_twice('---+')
    print()
square1()

def square2():
    print('+', end='')
    print_three('---+')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('+', end='')
    print_three('---+')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('+', end='')
    print_three('---+')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('+', end='')
    print_three('---+')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('|', end='')
    print_three('   |')
    print()
    print('+', end='')
    print_three('---+')
square2()